import { Inter } from "next/font/google";
import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";
import style from "./layout.module.css";
import Navbar from "@/Components/Navbar";
import Sidebar from "@/Components/Sidebar";

const InterSans = Inter();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${InterSans.className}`}>
        <div className={style.layout_container}>
          <Sidebar />
          <div className={style.right_section}>
            <Navbar />
            <main className={style.main}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
